
name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Magisk Module
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: Setup git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Compile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./compile.sh
    - name: Upload Result
      uses: actions/upload-artifact@v3
      with:
        name: ReVancedRepackaged.zip
        path: |
          ReVancedRepackaged-*.zip
        if-no-files-found: error
